# Generated by Django 5.2.1 on 2025-06-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickApp', '0002_librarycourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarycourse',
            name='course_choices',
            field=models.CharField(choices=[('WD', 'Web Development'), ('MD', 'Mobile Developement'), ('PRL', 'Programming Language'), ('ED', 'Educational Courses'), ('AR', 'Arabic Courses')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
