# Generated by Django 5.2.1 on 2025-06-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuickApp', '0003_librarycourse_course_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarycourse',
            name='reference',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
